name: Continuous Delivery

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    branches: ["main"]
    types:
      - completed

jobs:
  Publish:
    name: Publish to Cloudflare Workers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.5
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Release Projects
        run: yarn run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
